name: Assign Reviewers Based on Branch

on:
  pull_request:
    types: [opened]

permissions:
  contents: read
  pull-requests: write

jobs:
  assign-reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: Assign Reviewers
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // Definimos el revisor (tú)
            const reviewers = ['konozca-joel-fernandez'];

            // Ejecutamos la petición de revisión
            await github.rest.pulls.requestReviewers({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              reviewers: reviewers
            });
