public with sharing class ONE_PedidoCateringData {

    public String centro {public get; private set;}
    public String asesor {public get; private set;}
    public String nServicio {public get; private set;}
    public String nPedido {public get; private set;}
    public String fechaPedido {public get; private set;}
    public String proveedor {public get; private set;}
    public String difunto {public get; private set;}



}