public class ONE_SalaExternaData {

    
    public String logoUrl {public get; private set;}
    public String documentCode {public get; private set;}
    public String Lugar_de_velacion {get; set;} 
    public String N_Servicio {get; set;}
    public String ONE_Sala_N {get; set;}
    public String ONE_Fecha_Reserva {get; set;}
	public String ONE_Atendido_por {get; set;}
    public String NombreDifunto {get; set;}
    public String DNI {get; set;}
    public String ONE_Causas_de_Defuncion {get; set;}
    public String ONE_Judicial {get; set;}
    public String ONE_N_Juzgado {get; set;}
    public String ONE_Ultimo_Domicilio {get; set;}
    public String ONE_LugarDefuncion {get; set;}
    
    
    
    public String Nombre {get; set;}
    public String ONE_Direccion{get; set;}
    public String DNI_Tanatopractor{get; set;}
    public String Correo_electronico{get; set;}
    public String ONE_Autoriza_Pantallas{get; set;}
    public String ONE_Autoriza_Pantallas_Checkbox{get; set;}
    public String ONE_Autoriza_Web{get; set;}
    public String ONE_Autoriza_Web_Checkbox{get; set;}
    public String ONE_Servicio_Sala{get; set;}
    public String ONE_Exposici_n_F_retro{get; set;}
    public String ONE_Fecha_Hora_Entrada_Sala{get; set;}
    public String ONE_Fecha_Hora_Salida_Sala{get; set;}
    public String ONE_Despedida_Familiar{get; set;}
    public String ONE_Estancia_en_c_maras{get; set;}
    public String  Libro_de_firmas{get; set;}
    public String  ONE_Sala_preparaci_n{get; set;}
    public String  ONE_Ceremonia_religiosa{get; set;}
     public String ONE_Preparaci_n_fallecido_a{get; set;}
     public String ONE_Ceremonia_laica{get; set;}
     public String ONE_Catering_n_mero{get; set;}
    public String  ONE_M_sica_interpretes_n_mero{get; set;}
    public String  ONE_Hora{get; set;}
   public String   ONE_Custodia_Manipulaci_n_flores{get; set;}
    public String  Lugar_ceremonia{get; set;}
    public String  Fecha_hora_ceremonia_2{get; set;}
     public String Destino{get; set;}
     public String Fecha_hora_destino_final{get; set;}
    public String  Observaciones2{get; set;}
    public String  NIF{get; set;}
    public String  ONE_auxPagador{get; set;}
    public String  ONE_Tratamiento_Datos_Personales_Reserva{get; set;}
    public String  ONE_Fdo{get; set;}
    public String  ONE_Empresa{get; set;}   
                    
                    
    public String ONE_El_que_subscribe {public get; private set;} 
    public String ONE_Domicialiado_en_Poblacion {public get; private set;} 
    public String ONE_Poblacion {public get; private set;} 
    public String ONE_Documento_de_Identidad_Subscriptor {public get; private set;} 
    public String ONE_Email_Texto {public get; private set;} 
    public String ONE_Codigo_Postal {public get; private set;} 
    public String ONE_Provincia {public get; private set;} 
    public String ONE_Parentesco {public get; private set;} 
    public String ONE_Telefono {public get; private set;} 
    public String ONE_Tipo_de_Difunto {public get; private set;} 
    public String ONE_Difunto {public get; private set;} 
    public String ONE_Documento_de_Identidad_Difunto {public get; private set;} 
    public String ONE_Lugar_de_Fallecimiento {public get; private set;} 
    public String ONE_Fallecido_en_fecha {public get; private set;} 
    public String ONE_Estado_del_difunto {public get; private set;} 
    public Integer ONE_Edad_Difunto {public get; private set;} 
    public String ONE_Domicilio_Mortuorio {public get; private set;}  
    public String ONE_Funeraria {public get; private set;} 
    public String ONE_Feretro_Caracteristicas {public get; private set;} 
    public String ONE_Largo_ext {public get; private set;} 
    public String ONE_Ancho_ext {public get; private set;} 
    public String ONE_Alto_ext {public get; private set;} 
    public String ONE_SOLICITA_la_incineracion_de {public get; private set;} 
    public String ONE_Fecha_Now {public get; private set;} 
    public String Responso_en_el_cementerio {public get; private set;} 
    public String ONE_Concesion {public get; private set;} 
    public String ONE_Tipo_de_enterramiento {public get; private set;} 
    public String ONE_Temporalidad {public get; private set;} 
    public String ONE_Datos_de_la_unidad {public get; private set;} 
    public String ONE_Donde_se_encuentra {public get; private set;} 
    public String ONE_Observaciones {public get; private set;} 
    public String ONE_Nombre_y_apellidos_1 {public get; private set;} 
    public String ONE_Fecha_de_Inhumacion_1 {public get; private set;} 
    public String ONE_Nombre_y_apellidos_2 {public get; private set;} 
    public String ONE_Fecha_de_Inhumacion_2 {public get; private set;} 
    public String ONE_Nombre_y_apellidos_3 {public get; private set;} 
    public String ONE_Fecha_de_Inhumacion_3 {public get; private set;} 
    public String ONE_Nombre_y_apellidos_4 {public get; private set;} 
    public String ONE_Fecha_de_Inhumacion_4 {public get; private set;} 
    public String ONE_Se_dispone_de_t_tulo_funerario {public get; private set;} 
    public Boolean ONE_Se_conocen_las_tasas_de_conservacion {public get; private set;} 
    public String ONE_Vinculadacion_al_difunto_por_razon {public get; private set;} 
    public String ONE_Grado_de_consanguinidad {public get; private set;} 
    public String ONE_Grado_de_afinidad {public get; private set;} 
    public String En_Lugar {public get; private set;}
    public String Fecha_Now {public get; private set;}
    public String capturaDeFirmaUrl {public get; private set;}
    public Boolean isSignatureEmpty {public get; private set;}
    public String ONE_Doc_Existencia_Tasas_De_Conservacion {public get; private set;}
    public String ONE_Doc_Dispone_Titulo_Funerario {public get; private set;}
    public String ONE_Doc_La_Familia_Solicita {public get; private set;}
    public String ONE_Doc_Unidad_Enterramiento_Inhumado {public get; private set;}
    public String language {public get; private set;}
    public String ONE_Municipio {public get; private set;}
    public String ONE_Fecha_de_Inhumacion_de_solicitud {public get; private set;}
    public String observacionesInhumacion {public get; private set;}
    public String ONE_PoblacionDifunto {public get; private set;}
    public String ONE_Heredero {public get; private set;}
    public String ONE_Titular {public get; private set;}
    public String ONE_Fecha_Inhumacion {public get; private set;}
    public String sociedad {public get; private set;}
    public String footerInformation {public get; private set;}
    public String ONE_Doc_Exhumacion {public get; private set;}
    public String ONE_Doc_Inicio_Exhumacion {public get; private set;}
    public String ONE_Municipio_Exhumacion {public get; private set;}
    public String ONE_Doc_Fin_Exhumacion {public get; private set;}
    public String ONE_Restos_De {public get; private set;}
    public String ONE_Codigo_Postal_Exhumacion {public get; private set;}
    public String ONE_Localizacion_Unidad_Exhumacion  {public get; private set;}
    public String ONE_Presente_En_Exhumacion  {public get; private set;}
    public String ONE_Tipo_De_Unidad {public get; private set;}
    public String ONE_Destruccion_De_La_Lapida {public get; private set;}
    public String ONE_Observaciones_Exhumacion {public get; private set;}
    public String ONE_Destino_Ornamentaci_n {public get; private set;}
    public String ONE_Finalidad_Exhumacion {public get; private set;}
        
        public ONE_SalaExternaData(String docCode, ONE_Documentos__c documento, String signatureUrl, String language ) {
			
            logoUrl = documento.ONE_Servicio__r?.ONE_Centro_Del_Expediente__r?.ONE_URL_logo__c != null
                ? documento.ONE_Servicio__r.ONE_Centro_Del_Expediente__r.ONE_URL_logo__c
                : documento.ONE_Servicio__r?.ONE_Centro_Del_Expediente__r?.ONE_Sociedad2__r?.ONE_URL_logo__c;
            documentCode = docCode; 
        	ONE_Fecha_de_Inhumacion_de_solicitud = documento.ONE_Fecha_de_Inhumacion_de_solicitud__c?.format();
            Lugar_de_velacion = documento.Lugar_de_velacion__c;
            N_Servicio = documento.N_Servicio__c;
            ONE_Sala_N = documento.ONE_Sala_N__c;
            ONE_Fecha_Reserva = documento.ONE_Fecha_Reserva__c != null? documento.ONE_Fecha_Reserva__c.format() :'';
			ONE_Atendido_por = documento.ONE_Atendido_por__c;
            
			NombreDifunto = documento.NombreDifunto__c;
            DNI  = documento.DNI__c;
            ONE_Causas_de_Defuncion  = documento.ONE_Causas_de_Defuncion__c;
            ONE_Judicial  = documento.ONE_Judicial__c ?'/img/checkbox_checked.gif': '/img/checkbox_unchecked.gif';
            ONE_LugarDefuncion  = documento.ONE_LugarDefuncion__c;
            ONE_N_Juzgado  = documento.ONE_N_Juzgado__c;
            ONE_Ultimo_Domicilio = documento.ONE_Ultimo_Domicilio__c;
            ONE_LugarDefuncion = documento.ONE_LugarDefuncion__c;
            
            
     Nombre = documento.Nombre__c;
     ONE_Direccion = documento.ONE_Direccion__c;
     DNI_Tanatopractor = documento.DNI_Tanatopractor__c;
     Correo_electronico = documento.Correo_electronico__c;
     ONE_Autoriza_Pantallas = documento.ONE_Autoriza_Pantallas__c; 
     ONE_Autoriza_Pantallas_Checkbox = documento.ONE_Autoriza_Pantallas_Checkbox__c ?'/img/checkbox_checked.gif': '/img/checkbox_unchecked.gif';
     ONE_Autoriza_Web = documento.ONE_Autoriza_Web__c;
     ONE_Autoriza_Web_Checkbox = documento.ONE_Autoriza_Web_Checkbox__c ?'/img/checkbox_checked.gif': '/img/checkbox_unchecked.gif';
     ONE_Servicio_Sala = documento.ONE_Servicio_Sala__c  ?'/img/checkbox_checked.gif': '/img/checkbox_unchecked.gif';
     ONE_Exposici_n_F_retro = documento.ONE_Exposici_n_F_retro__c;
     ONE_Fecha_Hora_Entrada_Sala = documento.ONE_Fecha_Hora_Entrada_Sala__c?.format();
     ONE_Fecha_Hora_Salida_Sala = documento.ONE_Fecha_Hora_Salida_Sala__c?.format();
     ONE_Despedida_Familiar = documento.ONE_Despedida_Familiar__c ?'/img/checkbox_checked.gif': '/img/checkbox_unchecked.gif';
     ONE_Estancia_en_c_maras = documento.ONE_Estancia_en_c_maras__c ?'/img/checkbox_checked.gif': '/img/checkbox_unchecked.gif';
      Libro_de_firmas = documento.Libro_de_firmas__c ?'/img/checkbox_checked.gif': '/img/checkbox_unchecked.gif';
      ONE_Sala_preparaci_n = documento.ONE_Sala_preparaci_n__c ?'/img/checkbox_checked.gif': '/img/checkbox_unchecked.gif';
      ONE_Ceremonia_religiosa = documento.ONE_Ceremonia_religiosa__c ?'/img/checkbox_checked.gif': '/img/checkbox_unchecked.gif';
      ONE_Preparaci_n_fallecido_a = documento.ONE_Preparaci_n_fallecido_a__c ?'/img/checkbox_checked.gif': '/img/checkbox_unchecked.gif';
      ONE_Ceremonia_laica = documento.ONE_Ceremonia_laica__c ?'/img/checkbox_checked.gif': '/img/checkbox_unchecked.gif';
      ONE_Catering_n_mero = documento.ONE_Catering_n_mero__c ?'/img/checkbox_checked.gif': '/img/checkbox_unchecked.gif';
      ONE_M_sica_interpretes_n_mero = documento.ONE_M_sica_interpretes_n_mero__c ?'/img/checkbox_checked.gif': '/img/checkbox_unchecked.gif';
      ONE_Hora = documento.ONE_Hora__c?.format();
      ONE_Custodia_Manipulaci_n_flores = documento.ONE_Custodia_Manipulaci_n_flores__c ?'/img/checkbox_checked.gif': '/img/checkbox_unchecked.gif';
      Lugar_ceremonia = documento.Lugar_ceremonia__r.Name;
      Fecha_hora_ceremonia_2 = documento.Fecha_hora_ceremonia_2__c?.format();
      Destino = documento.Destino__c;
      Fecha_hora_destino_final = documento.Fecha_hora_destino_final__c?.format();
      Observaciones2 = documento.Observaciones2__c;
      NIF = documento.NIF__c;
      ONE_auxPagador = documento.ONE_auxPagador__c;
      ONE_Tratamiento_Datos_Personales_Reserva = documento.ONE_Tratamiento_Datos_Personales_Reserva__c;
      ONE_Fdo = documento.ONE_Fdo__c;
      ONE_Empresa = documento.ONE_Empresa__c;
            
            
            
            
            
            
            
            
            
            
            ONE_El_que_subscribe = documento.ONE_El_que_subscribe__c;
            ONE_Domicialiado_en_Poblacion = documento.ONE_Domicialiado_en_Poblacion__c;
            ONE_Poblacion = documento.ONE_Poblacion__c;
            ONE_Documento_de_Identidad_Subscriptor = documento.ONE_Documento_de_Identidad_Subscriptor__c;
            ONE_Email_Texto = documento.ONE_Email_Texto__c;
            ONE_Codigo_Postal = documento.ONE_Codigo_Postal__c;
            ONE_Provincia = documento.ONE_Provincia2__c;
            ONE_Parentesco = documento.ONE_Parentesco__c;
            ONE_Telefono = documento.ONE_Telefono__c;
            ONE_Tipo_de_Difunto = documento.ONE_Tipo_de_Difunto__c;
            ONE_Difunto = documento.ONE_Difunto__c;
            ONE_Documento_de_Identidad_Difunto = documento.ONE_Documento_de_Identidad_Difunto__c;
            ONE_Lugar_de_Fallecimiento = documento.ONE_Lugar_de_Fallecimiento__c;
            ONE_Fallecido_en_fecha = documento.ONE_Fallecido_en_fecha__c != null? documento.ONE_Fallecido_en_fecha__c.format() :'';
            ONE_Estado_del_difunto = documento.ONE_Estado_del_difunto__c;
            ONE_Edad_Difunto = documento.ONE_Edad_Difunto__c != null? documento.ONE_Edad_Difunto__c.intValue(): null;
            ONE_Domicilio_Mortuorio = documento.ONE_Servicio__r?.ONE_Velacion__c && documento.ONE_Servicio__r?.ONE_Lugar_De_Velacion__r?.Name!=null ? documento.ONE_Servicio__r?.ONE_Lugar_De_Velacion__r?.Name: '' ;
            ONE_Funeraria = documento.ONE_Servicio__r?.ONE_Centro_Del_Expediente__r?.ONE_Sociedad2__r?.Name;
            ONE_Feretro_Caracteristicas = documento.ONE_Feretro_Caracteristicas__c;
            ONE_Largo_ext = documento.ONE_Largo_ext__c;
            ONE_Ancho_ext = documento.ONE_Ancho_ext__c;
            ONE_Alto_ext = documento.ONE_Alto_ext__c;
            ONE_SOLICITA_la_incineracion_de = documento.ONE_SOLICITA_la_incineracion_de__c;
            ONE_Causas_de_Defuncion = documento.ONE_Causas_de_Defuncion__c;
            ONE_Fecha_Now = documento.ONE_Fecha_Now__c != null? documento.ONE_Fecha_Now__c.format() :'';
            Responso_en_el_cementerio = documento.Responso_en_el_cementerio__c;
            ONE_Concesion = documento.ONE_Concesion__c;
            ONE_Tipo_de_enterramiento = documento.ONE_Tipo_de_enterramiento__c != null? documento.ONE_Tipo_de_enterramiento__c : 'Inhumación';
            ONE_Temporalidad = documento.ONE_Temporalidad__c; 
            ONE_Datos_de_la_unidad = documento.ONE_Datos_de_la_unidad__c;
            ONE_Donde_se_encuentra = documento.ONE_Donde_se_encuentra__c;
            ONE_Observaciones = documento.ONE_Observaciones__c;
            ONE_Nombre_y_apellidos_1 = documento.ONE_Nombre_y_apellidos_1__c;
            ONE_Fecha_de_Inhumacion_1 = documento.ONE_Fecha_de_Inhumacion_1__c != null? documento.ONE_Fecha_de_Inhumacion_1__c.format() :'';
            ONE_Nombre_y_apellidos_2 = documento.ONE_Nombre_y_apellidos_2__c;
            ONE_Fecha_de_Inhumacion_2 = documento.ONE_Fecha_de_Inhumacion_2__c != null? documento.ONE_Fecha_de_Inhumacion_2__c.format() :'';
            ONE_Nombre_y_apellidos_3 = documento.ONE_Nombre_y_apellidos_3__c;
            ONE_Fecha_de_Inhumacion_3 = documento.ONE_Fecha_de_Inhumacion_3__c != null? documento.ONE_Fecha_de_Inhumacion_3__c.format() :'';
            ONE_Nombre_y_apellidos_4 = documento.ONE_Nombre_y_apellidos_4__c;
            ONE_Fecha_de_Inhumacion_4 = documento.ONE_Fecha_de_Inhumacion_4__c != null? documento.ONE_Fecha_de_Inhumacion_4__c.format() :'';
            ONE_Se_conocen_las_tasas_de_conservacion = documento.ONE_Se_conocen_las_tasas_de_conservacion__c;
            ONE_Vinculadacion_al_difunto_por_razon = documento.ONE_Vinculadacion_al_difunto_por_razon__c;
        	ONE_Doc_Unidad_Enterramiento_Inhumado  = documento.ONE_Se_encuentra_inhumado__c;
            ONE_Grado_de_consanguinidad = documento.ONE_Grado_de_consanguinidad__c;
            ONE_Grado_de_afinidad = documento.ONE_Grado_de_afinidad__c;
        	ONE_Doc_Existencia_Tasas_De_Conservacion =documento.ONE_Se_conocen_las_tasas_de_conservacion__c ?'/img/checkbox_checked.gif': '/img/checkbox_unchecked.gif';
            ONE_Doc_Dispone_Titulo_Funerario = documento.ONE_Se_dispone_de_t_tulo_funerario__c	?'/img/checkbox_checked.gif': '/img/checkbox_unchecked.gif';
            ONE_Doc_La_Familia_Solicita = documento.ONE_La_familia_solicita__c ?'/img/checkbox_checked.gif': '/img/checkbox_unchecked.gif';
        	ONE_Municipio = documento.ONE_Servicio__r?.ONE_Centro_Del_Expediente__r?.ONE_Municipio__r?.Name;
            En_Lugar = documento.ONE_En_Lugar__r.Name;
            Fecha_Now = documento.ONE_Fecha_Now__c.format('dd/MM/yyyy HH:mm');
            this.capturaDeFirmaUrl = signatureUrl;
            this.isSignatureEmpty = capturaDeFirmaUrl == '' ? true : false;
        	this.language = language;
        	observacionesInhumacion= documento.ONE_Observaciones__c;
        	ONE_PoblacionDifunto=documento.ONE_Servicio__r?.ONE_Difunto__r?.ONE_Municipio__pc;
        	ONE_Heredero= documento.ONE_Heredero__c ?'/img/checkbox_checked.gif': '/img/checkbox_unchecked.gif';
            ONE_Titular= documento.ONE_Titular__c ?'/img/checkbox_checked.gif': '/img/checkbox_unchecked.gif';
        	ONE_Fecha_Inhumacion=documento.Fecha_inhumacion_Unidad_Enterramiento__c?.format();
        	this.sociedad = documento.ONE_Servicio__r.ONE_Centro_Del_Expediente__r.ONE_Sociedad2__r.Name != null 
                ? documento.ONE_Servicio__r.ONE_Centro_Del_Expediente__r.ONE_Sociedad2__r.Name
                : '';
        	this.footerInformation = documento.ONE_Servicio__r.ONE_Centro_Del_Expediente__r.ONE_Sociedad2__r.ONE_Pie_de_pagina__c != null 
                ? documento.ONE_Servicio__r.ONE_Centro_Del_Expediente__r.ONE_Sociedad2__r.ONE_Pie_de_pagina__c
                : '';
        
            ONE_Doc_Exhumacion = documento.ONE_Lugar_Exhumacion__c;
			ONE_Doc_Inicio_Exhumacion = documento.ONE_Inicio_Exhumaci_n__c?.format();
    		ONE_Municipio_Exhumacion = documento.ONE_Municipio_Exhumaci_n__c;
			ONE_Doc_Fin_Exhumacion = documento.ONE_Fin_Exhumaci_n__c?.format();
         	ONE_Restos_De = documento.ONE_Restos_de__c;
			ONE_Codigo_Postal_Exhumacion = documento.ONE_C_digo_postal_Exhumaci_n__c;
   			ONE_Localizacion_Unidad_Exhumacion  = documento.ONE_Localizaci_n_Unidad_Exhumaci_n__c;
    		ONE_Presente_En_Exhumacion  = documento.Presente_en_Exhumaci_n__c ?'/img/checkbox_checked.gif': '/img/checkbox_unchecked.gif';
   			ONE_Tipo_De_Unidad = documento.ONE_Unidad_de_Exhumacion__c;
			ONE_Destruccion_De_La_Lapida = documento.ONE_Destrucci_n_de_la_L_pida__c  ?'/img/checkbox_checked.gif': '/img/checkbox_unchecked.gif';
    		ONE_Observaciones_Exhumacion = documento.ONE_Observaciones_Exhumacion__c;
    		ONE_Destino_Ornamentaci_n = documento.ONE_Destino_Ornamentaci_n__c;
    		ONE_Finalidad_Exhumacion = documento.ONE_Finalidad_Exhumaci_n__c;
    }


}