/**
 * Created by mbujak003 on 02.12.2020.
 */

public with sharing class ONE_CommonConstants {

    public static final String LUGAR = 'ONE_Lugar__c';
    public static final String ACCOUNT = 'Account';
    public static final String RECURSOS_INTERNOS = 'ONE_Recursos_Internos__c';
    public static final String EXPEDIENTE = 'ONE_Expediente__c';
    public static final String ORDEN_DE_VENTA = 'ONE_Orden_De_Venta__c';
    public static final String EXPEDIENTE_LINE_ITEM = 'ONE_Expediente_Line_Item__c';
    public static final String TAREA = 'ONE_Tarea__c';
    public static final String INTERLOCUTOR = 'ONE_Interlocutor__c';
    public static final String CONTRATO = 'ONE_Contrato__c';
    public static final String PRESUPUESTO = 'ONE_Presupuesto__c';

    public static final String ACC_RT_CENTRO_MEMORA = 'ONE_Centro_Memora';
    public static final String ACC_RT_OTRAS_CUENTAS = 'ONE_Otras_Cuentas';
    public static final String ACC_RT_ACCOUNT_SOCIEDADES = 'ONE_Sociedades';

    public static final String ACC_RT_PERSON_ACCOUNT_PARTICULAR = 'ONE_Person_Accout_Particular';
    public static final String ACC_RT_PERSON_ACCOUNT_PROFESIONAL = 'ONE_Person_Account_Profesional';
    public static final String EXP_RT_SERVICIO_DEFUNC = 'ONE_Servicio_Defuncion';
    public static final String INT_RT_INTERLOCUTOR = 'ONE_Interlocutor';
    public static final String PRES_RT_PRESUPUESTO_APP = 'ONE_Presupuesto_App';

    public static final String TAREA_RT_TAREA_DE_CONDUCCION = 'ONE_Tarea_De_Conduccion';
    public static final String TAREA_RT_TAREA_DE_VEHICULO_DE_ACOMPANIAMIENTO = 'ONE_Tarea_De_Vehiculo_De_Acompanamiento';
    public static final String TAREA_RT_TAREA_DE_FLORES = 'ONE_Tarea_De_Flores';
    public static final String TAREA_RT_TAREA_DE_ALMACEN_NAME = 'Tarea de almacén';
    public static final String TAREA_RT_TAREA_DE_ALMACEN = 'ONE_Tarea_De_Almacen';

    public static final String REC_RT_SALAS = 'ONE_Salas';

    public static final String CONT_RT_M1 = 'ONE_Contrato_M1';
    public static final String CONT_RT_ELECTIUM = 'ONE_Contrato_Electium';

    public static final String ICO_ACCOUNT = 'standard:account';

    public static final String MOMENTO_VELACION = 'Velación';
    public static final String MOMENTO_CEREMONIA = 'Ceremonia';
    public static final String MOMENTO_CREMACION = 'Cremación';
    public static final String MOMENTO_CEMENTERIO = 'Cementerio';
    public static final String MOMENTO_DEPOSITO = 'Depósito';
    public static final String MOMENTO_DESPEDIDA = 'Despedida';

    public static final String CEMETERY_CODE_2 = '2';

    public static final String ESTADO_CONFIRMADO = 'Confirmado';
    public static final String ESTADO_COBRADO = 'Cobrado';
    public static final String ESTADO_ENVIADO = 'Enviado';
    public static final String ESTADO_REENVIADO = 'Reenviado';
    public static final String ESTADO_PENDIENTE = 'Pendiente';
    public static final String ESTADO_ABONADO = 'Abonado';

    public static final String RELACION_COMPLEMENTO = 'Complemento';
    public static final String RELACION_PACK = 'Pack';

    public static final String PRODUCTO_PACK = 'Pack';
    public static final String PRODUCT_PRECIO_UNICO = 'Precio único';
    public static final String PRODUCT_PRECIO_INDEXADO = 'Precio indexado';

    public static final String CM_SAP_OAUTH = 'SAP_OAUTH';
    public static final String CM_SAP_CONSULTASTOCKS = 'SAP_CONSULTASTOCKS';
    public static final String CM_SAP_PURCHASEORDER = 'SAP_PURCHASEORDER';
    public static final String CM_SAP_SALESORDER = 'SAP_SALESORDER';
    public static final String CM_SAP_ELECTIUM_CLIENT_CREATE = 'ELECTIUM_CLIENTES';
    public static final String CM_SAP_ELECTIUM_COBROS = 'SAP_ELECTUM_COBROS';
    public static final String CM_SAP_ELECTIUM_MES_COBROS = 'SAP_ELECTIUM_MES_COBROS';
    public static final String CM_SAP_SEPAMANDATE = 'SAP_SEPAMANDATE';
    public static final String CM_SAP_ZONECUSTOMER = 'SAP_ZONECUSTOMER';
    public static final String CM_SAP_RESERVA_STOCK = 'SAP_RESERVA_STOCK';
    public static final String CM_SAP_CANCELINVOICE = 'SAP_CANCELINVOICE';
    public static final String CM_SAP_ZONE_ELECTIUM = 'SAP_ZONE_ELECTIUM';
    public static final String CM_SAP_CANCELSTOCK = 'SAP_CANCELSTOCK';
    public static final String CM_SAP_CONSUMOS = 'SAP_CONSUMOS';
    public static final String CM_SAP_CANCELCONSUMO = 'SAP_CANCELCONSUMO';
    public static final String CM_SAP_TPV_PAYMENT = 'SAP_TPV_PAYMENT';
    public static final String CM_SAP_STOCKMOVEMENT = 'SAP_STOCKMOVEMENT';
    public static final String CM_CAJAMAR_LOGIN = 'CAJAMAR_LOGIN';
    public static final String CM_GENERALI_LOGIN = 'GENERALI_LOGIN';
    public static final String CM_CAJAMAR_SERVALIDA = 'CAJAMAR_SERVALIDA';
    public static final String CM_GENERALI_SERVALIDA = 'GENERALI_SERVALIDA';
    public static final String CM_GENERALI_OPEN_LIFE_CLAIM = 'GENERALI_OPEN_LIFE_CLAIM';
    public static final String CM_CAJAMAR_OPEN_LIFE_CLAIM = 'CAJAMAR_OPEN_LIFE_CLAIM';
    public static final String CM_OPINAT_LEAD_SERVICE = 'OPINAT_LEAD_SERVICE';
    public static final String CM_APLICACION = 'APLICACION';
    public static final String CM_FUNEFLOR = 'FUNEFLOR';
    public static final String CM_FLORESMEMORA = 'FLORESMEMORA';
    public static final String CM_MEDIAGEN = 'MEDIAGEN';
    public static final String CM_FROTCOM_AUTHORIZE = 'FROTCOM_AUTHORIZE';
    public static final String CM_FROTCOM_SEND_TASKS = 'FROTCOM_SEND_TASKS';
    public static final String CM_CODIGO_DE_DOCUMENTO_DATOS_BASICOS = 'ONE_Datos_Basicos';
    public static final String CM_CAJAMAR_NEW_BUDGET = 'CAJAMAR_NEW_BUDGET';
    public static final String CM_GENERALI_NEW_BUDGET = 'GENERALI_NEW_BUDGET';
    public static final String CM_CAJAMAR_EDIT_BUDGET = 'CAJAMAR_EDIT_BUDGET';
    public static final String CM_GENERALI_EDIT_BUDGET = 'GENERALI_EDIT_BUDGET';
    public static final String CM_CAJAMAR_INVOICE = 'CAJAMAR_INVOICE';
    public static final String CM_GENERALI_INVOICE = 'GENERALI_INVOICE';
    public static final String CM_CAJAMAR_BASE64 = 'CAJAMAR_BASE64';
    public static final String CM_GENERALI_BASE64 = 'GENERALI_BASE64';
    public static final String CM_KUTXABANK = 'KUTXABANK';
    public static final String CM_MIDDLEWARE_KBS_CP = 'MIDDLEWARE_KBS_CONSULTA_POLIZA';
    public static final String CM_MIDDLEWARE_KBS_AS = 'MIDDLEWARE_KBS_ALTA_SINIESTRO';
    public static final String CM_MIDDLEWARE_KBS_AS_NOLOGS = 'MIDDLEWARE_KBS_ALTA_SINIESTRO_NOLOGS';
    public static final String CM_MIDDLEWARE_KBS_AF = 'MIDDLEWARE_KBS_ALTA_FACTURA';
    public static final String CM_MIDDLEWARE_KBS_AF_NOLOGS = 'MIDDLEWARE_KBS_ALTA_FACTURA_NOLOGS';

    public static final String PROFILE_SYSADMIN = 'System Administrator';
    public static final String PROFILE_SYSADMIN_ES = 'Administrador del sistema';
    public static final String PROFILE_PLANIFICADOR = 'Planificador';
    public static final String PROFILE_POLIVALENTE = 'Polivalente';
    public static final String PROFILE_ASESOR = 'Asesor Comercial / Recepción';
    public static final String PROFILE_ASESOR_FACTURA = 'Asesor Comercial Factura';

    public static final String TIPO_DE_RECURSO_PROVEDOOR = 'Proveedor';
    public static final String TIPO_DE_RECURSO_CONDUCCION = 'Conducción';

    public static final String ESTADO_PENDIENTE_ASIGNAR = 'Pendiente de asignar';
    public static final String ESTADO_PENDIENTE_ACCEPTAR = 'Pendiente de aceptar';

    public static final String HTTP_METHOD_POST = 'POST';

    public static final Integer HTPP_SUCCESS_CODE = 200;
    public static final Integer HTPP_SUCCESS_CODE_CREATED = 201;
    public static final Integer HTTP_MOVED_TEMPORARILY_CODE = 302;
    public static final Integer HTTP_TEMPORARY_REDIRECT_CODE = 307;
    public static final Integer HTPP_SERVER_ERROR_CODE = 500;

    public static final String FOTO_QUEUE_NAME = 'ONE_Departamento_Legal_Fotos';

    public static final String TIME_FORMAT = 'k:mm';
    public static final String DATE_FORMAT = 'yyyy-MM-dd';

    public static final String EMAIL_TEMPLATE_DATOS_BASICA_DEV_NAME_ES = 'ONE_Datos_Basica_ES';
    public static final String EMAIL_TEMPLATE_DATOS_BASICA_DEV_NAME_CA = 'ONE_Datos_Basica_CA';
    public static final String EMAIL_TEMPLATE_DATOS_BASICA_DEV_NAME_EU = 'ONE_Datos_Basica_EU';

    public static final String EMAIL_TEMPLATE_CATERING_FLORES_MUSICA_VEHICULO_DEV_NAME_ES = 'ONE_Catering_Flores_Musica_Vehiculo_Template_ES';
    public static final String EMAIL_TEMPLATE_CATERING_FLORES_MUSICA_VEHICULO_DEV_NAME_CA = 'ONE_Catering_Flores_Musica_Vehiculo_Template_CA';
    public static final String EMAIL_TEMPLATE_CATERING_FLORES_MUSICA_VEHICULO_DEV_NAME_EU = 'ONE_Catering_Flores_Musica_Vehiculo_Template_EU';

    public static final String EMAIL_TEMPLATE_DATOS_PARROQUIALES_DEV_NAME_ES = 'ONE_Datos_Parroquiales_Template_ES';
    public static final String EMAIL_TEMPLATE_DATOS_PARROQUIALES_DEV_NAME_CA = 'ONE_Datos_Parroquiales_Template_CA';
    public static final String EMAIL_TEMPLATE_DATOS_PARROQUIALES_DEV_NAME_EU = 'ONE_Datos_Parroquiales_Template_EU';

    public static final String EMAIL_TEMPLATE_PEDIDO_INHUMACION_DEV_NAME_ES = 'ONE_Pedido_Inhumacion_Template_ES';
    public static final String EMAIL_TEMPLATE_PEDIDO_INHUMACION_DEV_NAME_CA = 'ONE_Pedido_Inhumacion_Template_CA';
    public static final String EMAIL_TEMPLATE_PEDIDO_INHUMACION_DEV_NAME_EU = 'ONE_Pedido_Inhumacion_Template_EU';

    public static final String EMAIL_TEMPLATE_MARMOLISTA_MEDICO_GESTORIA_ES = 'ONE_Template_Marmolista_Medico_Gestoria_ES';
    public static final String EMAIL_TEMPLATE_MARMOLISTA_MEDICO_GESTORIA_CA = 'ONE_Template_Marmolista_Medico_Gestoria_CA';
    public static final String EMAIL_TEMPLATE_MARMOLISTA_MEDICO_GESTORIA_EU = 'ONE_Template_Marmolista_Medico_Gestoria_EU';

    public static final String EMAIL_TEMPLATE_FACTURA_PDF_DEV_NAME_ES = 'ONE_Factura_Pdf_Template_ES';
    public static final String EMAIL_TEMPLATE_FACTURA_PDF_DEV_NAME_CA = 'ONE_Factura_Pdf_Template_CA';
    public static final String EMAIL_TEMPLATE_FACTURA_PDF_DEV_NAME_EU = 'ONE_Factura_Pdf_Template_EU';

    public static final String DOCUMENT_CODE_PEDIDO_CATERING = 'ONE_Pedido_Catering';
    public static final String DOCUMENT_CODE_PEDIDO_MUSICA = 'ONE_Pedido_Musica';
    public static final String DOCUMENT_CODE_PEDIDO_VEHICULOS = 'ONE_Pedido_Vehiculos_Acompanamiento';
    public static final String DOCUMENT_CODE_PEDIDO_FLORES = 'ONE_Pedido_Flores';
    public static final String DOCUMENT_CODE_PEDIDO_DATOS_PARROQUIALES = 'ONE_Datos_Parroquiales';
    public static final String DOCUMENT_CODE_AUTORIZACION_GENERAL = 'ONE_Autorizacion_General';
    public static final String DOCUMENT_CODE_SOLICITUD_INHUMACION = 'ONE_Solicitud_Inhumacion';
    public static final String DOCUMENT_CODE_SOLICITUD_INCINERACION = 'ONE_Solicitud_Incineracion';
    public static final String DOCUMENT_CODE_PROTECCION_DATOS = 'ONE_Autorizacion_Tratamiento';
    public static final String DOCUMENT_CODE_MARMOLISTA = 'ONE_Pedido_Marmolita';
    public static final String DOCUMENT_CODE_MEDICO = 'ONE_Pedido_Medico';
    public static final String DOCUMENT_CODE_GESTORIA = 'ONE_Pedido_Gestoria';
    public static final String DOCUMENT_CODE_HOJA_SERVICIO = 'ONE_Hoja_Servicio';
    public static final String DOCUMENT_CODE_SOLICITUD_EXHUMACION = 'ONE_Solicitud_Exhumacion';

    public static final String TAREA_TYPE_CATERING = 'Pedido de catering';
    public static final String TAREA_TYPE_MUSICA = 'Pedido de música';
    public static final String TAREA_TYPE_VEHICULO = 'Pedido de vehículo de acompañamiento';

    public static final String DOCUMENT_TAG_ABONO_COMERCIAL = 'ABONO_COMERCIAL';
    public static final String DOCUMENT_TAG_AUTORIZACION_GENERAL = 'AUTORIZACION_GENERAL';
    public static final String DOCUMENT_TAG_CONSERVACION_FRIO = 'CONSERVACION_FRIO';
    public static final String DOCUMENT_TAG_CONTRATO_COMERCIAL = 'CONTRATO_COMERCIAL';
    public static final String DOCUMENT_TAG_FACTURA_COMERCIAL = 'FACTURA_COMERCIAL';
    public static final String DOCUMENT_TAG_FACTURA_COMERCIAL_SIMPLIFICADA = 'FACTURA_COMERCIAL_SIMPLIFICADA';
    public static final String DOCUMENT_TAG_HOJA_SERVICIO = 'HOJA_SERVICIO';
    public static final String DOCUMENT_TAG_NECROLOGICA = 'NECROLOGICA';
    public static final String DOCUMENT_TAG_PEDIDO_GESTORIA = 'PEDIDO_GESTORIA';
    public static final String DOCUMENT_TAG_PEDIDO_MARMOLISTA = 'PEDIDO_MARMOLISTA';
    public static final String DOCUMENT_TAG_PEDIDO_MEDICO = 'PEDIDO_MEDICO';
    public static final String DOCUMENT_TAG_PRESUPUESTO = 'PRESUPUESTO';
    public static final String DOCUMENT_TAG_PROTECCION_DATOS = 'PROTECCION_DATOS';
    public static final String DOCUMENT_TAG_SOLICITUD_INCINERACION = 'SOLICITUD_INCINERACION';
    public static final String DOCUMENT_TAG_SOLICITUD_INHUMACION = 'SOLICITUD_INHUMACION';
    public static final String DOCUMENT_TAG_CERTIFICADO_MEDICO_DEFUNCION = 'CERTIFICADO_MEDICO_DEFUNCION';
    public static final String DOCUMENT_TAG_SUPLIDOS = 'SUPLIDOS';
    public static final String DOCUMENT_TAG_MODELO_01 = 'MODELO_01';
    public static final String DOCUMENT_TAG_SUPLIDO_SEGUR_CAIXA = 'SUPLIDO_SEGUR_CAIXA';
    public static final String DOCUMENT_TAG_SUPLIDO_OCASO = 'SUPLIDO_OCASO';
    public static final String DOCUMENT_TAG_SUPLIDO_CIA = 'SUPLIDO_CIA';
    public static final String DOCUMENT_TAG_FACTURA_RECTIFICATIVA = 'FACTURA_RECTIFICATIVA';
    public static final String DOCUMENT_TAG_CANCELACION_ABONO_PARCIAL = 'CANCELACION_ABONO_PARCIAL';
    public static final String DOCUMENT_TAG_SOLICITUD_EXHUMACION = 'SOLICITUD_EXHUMACION';
    public static final String DOCUMENT_TAG_FACTURA_CONCESIONALES = 'FACTURA_CONCESIONALES';

    public static final String TIPO_DE_PRESUPUESTO_WEB = 'Presupuesto web';

    public static final String TIPO_DE_CONTRATO_PARTICULAR = 'Particular';
    public static final String TIPO_DE_CONTRATO_SERVICIO = 'Hoja de servicio';

    public static final String DOCUMENT_TYPE_OTR = 'OTR';

    public static final String CASO_TIPO_GENERALI = 'Generali';
    public static final String CASO_TIPO_CAJAMAR = 'Cajamar';

    public static final String SAPSCOPE_ELECTIUM_CLIENTES = 'ZCRM_ELECTIUM_CLIENTES_SRV_0001';
    public static final String SAPSCOPE_CANCELCONSUMO = 'ZONE_CANCELCONSUMO_SRV_0001';
    public static final String SAPSCOPE_CANCELINVOICE = 'ZONE_CANCELINVOICE_SRV_0001';
    public static final String SAPSCOPE_CANCELSTOCK = 'ZONE_CANCELSTOCK_SRV_0001';
    public static final String SAPSCOPE_CONSUMOS = 'ZONE_CONSUMOS_SRV_0001';
    public static final String SAPSCOPE_CUSTOMER = 'ZONE_CUSTOMER_SRV_0001';
    public static final String SAPSCOPE_ELECTIUM_MES_COBROS = 'ZONE_ELECTIUM_MES_COBROS_SRV_0001';
    public static final String SAPSCOPE_ELECTIUM_COBROS = 'ZONE_ELECTIUM_COBROS_SRV_0001';
    public static final String SAPSCOPE_ELECTIUM = 'ZONE_ELECTIUM_SRV_0001';
    public static final String SAPSCOPE_PAYMENT = 'ZONE_PAYMENT_SRV_0001';
    public static final String SAPSCOPE_PURCHASEORDER = 'ZONE_PURCHASEORDER_SRV_01_0001';
    public static final String SAPSCOPE_SALESORDER = 'ZONE_SALESORDER_SRV_0001';
    public static final String SAPSCOPE_SEPA = 'ZONE_SEPA_SRV_0001';
    public static final String SAPSCOPE_STOCK = 'ZONE_STOCK_SRV_0001';
    public static final String SAPSCOPE_TRASLADOSMAT = 'ZONE_TRASLADOSMAT_SRV_0001';
}